In [1]:
import numpy as np

In [9]:
a1 = np.array([1,2,3])
a2 = np.array([[1,2,3],[4,5,6]])
a3 = np.array([[
    [1,2,3],
    [4,5,6],
    [7,8,9]
], [
    [10,11,13],
    [14,15,16],
    [17,18,19]
]])

In [4]:
a1.shape, a1.dtype, type(a1), a1.size

((3,), dtype('int64'), numpy.ndarray, 3)

In [5]:
a2.shape

(2, 3)

In [6]:
a2.size

6

In [7]:
a2.dtype, type(a2)

(dtype('int64'), numpy.ndarray)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
import pandas as pd

In [12]:
a2_df = pd.DataFrame(a2)

In [13]:
a2_df

0  1  2
0  1  2  3
1  4  5  6

In [15]:
np.ones((10,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
np.zeros((7,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [17]:
np.arange(0,100, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [18]:
np.random.randint(10, size=(7,2))

array([[3, 8],
       [5, 3],
       [7, 7],
       [5, 5],
       [3, 9],
       [1, 7],
       [9, 7]])

In [22]:
np.random.uniform(low=0, high=1, size=(3,5))

array([[0.00311141, 0.30305339, 0.67776729, 0.2857567 , 0.16829627],
       [0.91237295, 0.73997762, 0.9424689 , 0.21637393, 0.34904609],
       [0.62037727, 0.94599477, 0.16756624, 0.95756029, 0.72249991]])

In [23]:
np.random.random((3,5))

array([[0.97750934, 0.38051054, 0.37093142, 0.01014401, 0.72565328],
       [0.89263881, 0.34285408, 0.67519423, 0.35468213, 0.18373368],
       [0.1525895 , 0.71897949, 0.84904917, 0.13424029, 0.16517971]])

In [25]:
np.random.seed(42)
np.random.randint(10, size=(4,6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [32]:
random_numbers = np.random.randint(10, size=(3,7))

In [33]:
np.unique(random_numbers)

array([0, 1, 2, 3, 4, 5, 6, 7, 9])

In [34]:
random_numbers

array([[4, 1, 3, 6, 7, 2, 0],
       [3, 1, 7, 3, 1, 5, 5],
       [9, 3, 5, 1, 9, 1, 9]])

In [35]:
random_numbers[0]

array([4, 1, 3, 6, 7, 2, 0])

In [40]:
random_numbers[:2,:2]

array([[4, 1],
       [3, 1]])

In [41]:
random_numbers = np.random.randint(10,size=(3,5))
ones = np.ones((3,5))

In [42]:
random_numbers + ones

array([[ 4.,  8.,  7.,  9.,  8.],
       [ 5.,  2.,  5.,  8., 10.],
       [ 9.,  9.,  1.,  9.,  7.]])

In [44]:
new_ones = np.ones((5,3))

In [45]:
ones + new_ones

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [46]:
ones.shape

(3, 5)

In [47]:
new_ones.shape

(5, 3)

In [48]:
ones_2 = np.ones((3,5))

In [49]:
new_ones - ones_2

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

In [50]:
ones * ones_2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [51]:
ones.shape, ones_2.shape

((3, 5), (3, 5))

In [52]:
ones_2 ** ones_2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [53]:
np.square(ones_2)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [54]:
np.mean(ones_2)

1.0

In [55]:
np.max(ones_2)

1.0

In [56]:
np.mean(ones_2)

1.0

In [57]:
np.std(ones_2)

0.0

In [58]:
np.var(ones_2)

0.0

In [59]:
ones_2.reshape(3,5,1)

array([[[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.],
        [1.]]])

In [60]:
ones_2.T

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [63]:
random_array = np.random.randint(10, size=(3,3))
random_array_2 = np.random.randint(10, size=(3,2))

In [64]:
np.dot(random_array, random_array_2)

array([[52, 87],
       [40, 79],
       [14, 20]])

In [68]:
random_array = np.random.randint(10, size=(4,3))
random_array_2 = np.random.randint(10, size=(4,3))

In [69]:
random_array.dot(random_array_2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [70]:
random_array.dot(random_array_2.T)

array([[84, 58, 32, 49],
       [45, 20,  8,  0],
       [66, 61, 20, 49],
       [27, 51, 12, 56]])

In [71]:
array1 = np.random.randint(10, size=(2,3))
array2 = np.random.randint(10, size=(2,3))

In [72]:
array1 > array2

array([[ True, False,  True],
       [ True, False, False]])

In [73]:
array1 >= array2

array([[ True, False,  True],
       [ True, False, False]])

In [74]:
array1 > 7

array([[False, False, False],
       [False, False, False]])

In [75]:
array1 == array2

array([[False, False, False],
       [False, False, False]])

In [76]:
np.sort(array1)

array([[1, 1, 5],
       [0, 4, 6]])

In [77]:
np.argsort(array2)

array([[0, 2, 1],
       [0, 2, 1]])

In [78]:
np.argmax(array1)

3

In [79]:
np.argmax(array1, axis=1)

array([2, 0])

In [80]:
np.argmin(array2, axis=0)

array([0, 0, 0])

In [81]:
np.argmin(array1)

5

In [83]:
np.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [88]:
np.linspace(1,100,3)

array([  1. ,  50.5, 100. ])